// SPDX-License-Identifier: GPL-3.0-or-later
// Svelte 5 Runes store for diagnostic state.
// Using .svelte.ts extension so $state/$derived work outside components.
//
// Session 4 additions:
//   - _generatingReport: tracks bug report generation (drives spinner in UI)
//   - buildSummaryText(): client-side SUMMARY.txt builder (mirrors Rust logic)
//   - copySummaryText(): copies summary to clipboard, sets _copyFeedback briefly

import { invoke } from '@tauri-apps/api/core';
import type { DiagnosticReport, DiagnosticResult, CaptureTestResult, LayerLabel } from '$lib/types';

// ── State ──────────────────────────────────────────────────────────────────

let _report = $state<DiagnosticReport | null>(null);
let _running = $state(false);
let _fixing = $state<string | null>(null); // check name currently being fixed
let _fixLog = $state<string[]>([]);
let _captureResult = $state<CaptureTestResult | null>(null);
let _captureRunning = $state(false);
let _error = $state<string | null>(null);
let _generatingReport = $state(false); // true while generate_bug_report is in flight
let _copyFeedback = $state(false);     // true for 1.5 s after successful clipboard copy

// ── Derived ────────────────────────────────────────────────────────────────

const summary = $derived.by(() => {
	if (!_report) return { pass: 0, warn: 0, fail: 0 };
	return _report.summary;
});

const resultsByLayer = $derived.by(() => {
	if (!_report) return {} as Record<LayerLabel, DiagnosticResult[]>;
	return _report.results.reduce(
		(acc, r) => {
			const key = r.layer as LayerLabel;
			if (!acc[key]) acc[key] = [];
			acc[key].push(r);
			return acc;
		},
		{} as Record<LayerLabel, DiagnosticResult[]>
	);
});

const hasFailures = $derived(_report !== null && _report.summary.fail > 0);
const hasWarnings = $derived(_report !== null && _report.summary.warn > 0);

// ── Actions ────────────────────────────────────────────────────────────────

async function runDiagnostics() {
	_running = true;
	_error = null;
	_report = null;
	try {
		_report = await invoke<DiagnosticReport>('run_diagnostics');
	} catch (e) {
		_error = String(e);
	} finally {
		_running = false;
	}
}

async function executeFix(checkName: string, fixCommand: string) {
	_fixing = checkName;
	_fixLog = [];
	try {
		const output = await invoke<string>('execute_fix', { fixCommand });
		_fixLog = output.split('\n').filter(Boolean);
		// Re-run diagnostics after fix
		await runDiagnostics();
	} catch (e) {
		_error = String(e);
	} finally {
		_fixing = null;
	}
}

async function runCaptureTest() {
	_captureRunning = true;
	_captureResult = null;
	try {
		_captureResult = await invoke<CaptureTestResult>('run_capture_test');
	} catch (e) {
		_error = String(e);
	} finally {
		_captureRunning = false;
	}
}

async function generateBugReport(redact: boolean = false): Promise<string | null> {
	_generatingReport = true;
	try {
		return await invoke<string>('generate_bug_report', { redact });
	} catch (e) {
		_error = String(e);
		return null;
	} finally {
		_generatingReport = false;
	}
}

// ── SUMMARY.txt builder (mirrors build_summary_text in commands.rs) ────────

function buildSummaryText(report: DiagnosticReport): string {
	const fails = report.results.filter((r) => r.status === 'FAIL');
	const warns = report.results.filter((r) => r.status === 'WARN');
	const hr50 = '-'.repeat(50);
	const hr40 = '-'.repeat(40);
	const lines: string[] = [
		'wayland-spectre diagnostic report',
		'='.repeat(50),
		`Generated : ${report.system.generated_at}`,
		`Hostname  : ${report.system.hostname}`,
		`Kernel    : ${report.system.kernel}`,
		...(report.system.nvidia_driver ? [`NVIDIA    : ${report.system.nvidia_driver}`] : []),
		...(report.system.bazzite_image ? [`Bazzite   : ${report.system.bazzite_image}`] : []),
		'',
		`Summary: ${report.summary.pass} pass  ${report.summary.warn} warn  ${report.summary.fail} fail`,
		''
	];

	function appendSection(title: string, results: DiagnosticResult[]) {
		if (results.length === 0) return;
		lines.push(title, hr40);
		for (const r of results) {
			lines.push(`[${r.layer}] ${r.check}: ${r.detail}`);
			if (r.fix) lines.push(`  fix: ${r.fix}`);
			lines.push('');
		}
	}

	appendSection('FAILURES', fails);
	appendSection('WARNINGS', warns);

	lines.push(
		hr50,
		'Generated by wayland-spectre — https://forgejo.wanderingmonster.dev/WanderingMonster/wayland-spectre'
	);

	return lines.join('\n');
}

async function copySummaryText(): Promise<boolean> {
	if (!_report) return false;
	try {
		await navigator.clipboard.writeText(buildSummaryText(_report));
		_copyFeedback = true;
		setTimeout(() => {
			_copyFeedback = false;
		}, 1500);
		return true;
	} catch {
		_error = 'Clipboard write failed — try the bug report download instead.';
		return false;
	}
}

function clearError() {
	_error = null;
}

// ── Exported reactive object ───────────────────────────────────────────────

export const diagnostic = {
	// State (reactive via getters)
	get report() { return _report; },
	get running() { return _running; },
	get fixing() { return _fixing; },
	get fixLog() { return _fixLog; },
	get captureResult() { return _captureResult; },
	get captureRunning() { return _captureRunning; },
	get error() { return _error; },
	get generatingReport() { return _generatingReport; },
	get copyFeedback() { return _copyFeedback; },

	// Derived
	get summary() { return summary; },
	get resultsByLayer() { return resultsByLayer; },
	get hasFailures() { return hasFailures; },
	get hasWarnings() { return hasWarnings; },

	// Actions
	runDiagnostics,
	executeFix,
	runCaptureTest,
	generateBugReport,
	copySummaryText,
	clearError
};
